-- MySQL Script generated by MySQL Workbench
-- mié 19 may 2021 15:14:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CREA2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CREA2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CREA2` DEFAULT CHARACTER SET utf8mb4 ;
USE `CREA2` ;

-- -----------------------------------------------------
-- Table `CREA2`.`TypePlan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CREA2`.`TypePlan` (
  `pk_idTypePlan` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pk_idTypePlan`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CREA2`.`Plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CREA2`.`Plan` (
  `pk_idPlan` INT NOT NULL AUTO_INCREMENT,
  `fk_TypePlan` INT NOT NULL,
  `init_price` INT NOT NULL,
  `duration` INT NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`pk_idPlan`),
  INDEX `fk_Plan_TypePlan1_idx` (`fk_TypePlan` ASC) VISIBLE,
  CONSTRAINT `fk_Plan_TypePlan`
    FOREIGN KEY (`fk_TypePlan`)
    REFERENCES `CREA2`.`TypePlan` (`pk_idTypePlan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CREA2`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CREA2`.`Client` (
  `pk_idClient` INT NOT NULL AUTO_INCREMENT,
  `fk_Plan` INT NULL,
  `name` VARCHAR(45) NOT NULL,
  `user` VARCHAR(45) NULL,
  `password` VARCHAR(100) NOT NULL,
  `telephone` VARCHAR(11) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`pk_idClient`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_Client_Plan_idx` (`fk_Plan` ASC) VISIBLE,
  CONSTRAINT `fk_Client_Plan`
    FOREIGN KEY (`fk_Plan`)
    REFERENCES `CREA2`.`Plan` (`pk_idPlan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CREA2`.`Service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CREA2`.`Service` (
  `pk_idService` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `amount` INT NULL,
  `service_price` INT NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`pk_idService`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CREA2`.`Purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CREA2`.`Purchase` (
  `pk_idPurchase` INT NOT NULL AUTO_INCREMENT,
  `fk_Client` INT NOT NULL,
  `fk_Plan` INT NOT NULL,
  `fk_Subscription` INT NOT NULL,
  `transaction_date` DATETIME NOT NULL,
  `active` TINYINT(1) NOT NULL,
  PRIMARY KEY (`pk_idPurchase`),
  INDEX `fk_Purchase_Client_idx` (`fk_Client` ASC) VISIBLE,
  INDEX `fk_Purchase_Plan_idx` (`fk_Plan` ASC) VISIBLE,
  INDEX `fk_Purchase_Subscription_idx` (`fk_Subscription` ASC) VISIBLE,
  CONSTRAINT `fk_Purchase_Client`
    FOREIGN KEY (`fk_Client`)
    REFERENCES `CREA2`.`Client` (`pk_idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Purchase_Plan`
    FOREIGN KEY (`fk_Plan`)
    REFERENCES `CREA2`.`Plan` (`pk_idPlan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Purchase_Subscription`
    FOREIGN KEY (`fk_Subscription`)
    REFERENCES `CREA2`.`Subscription` (`pk_idSubscription`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CREA2`.`TypePlan_has_Service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CREA2`.`TypePlan_has_Service` (
  `pk_idTypePlan_has_Service` INT NOT NULL AUTO_INCREMENT,
  `fk_TypePlan` INT NOT NULL,
  `fk_Service` INT NOT NULL,
  PRIMARY KEY (`pk_idTypePlan_has_Service`),
  INDEX `fk_TypePlan_has_Service_Service_idx` (`fk_Service` ASC) VISIBLE,
  INDEX `fk_TypePlan_has_Service_TypePlan_idx` (`fk_TypePlan` ASC) VISIBLE,
  CONSTRAINT `fk_TypePlan_has_Service_TypePlan`
    FOREIGN KEY (`fk_TypePlan`)
    REFERENCES `CREA2`.`TypePlan` (`pk_idTypePlan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TypePlan_has_Service_Service`
    FOREIGN KEY (`fk_Service`)
    REFERENCES `CREA2`.`Service` (`pk_idService`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CREA2`.`Subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CREA2`.`Subscription` (
  `pk_idSubscription` INT NOT NULL AUTO_INCREMENT,
  `share` INT NOT NULL DEFAULT 1,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`pk_idSubscription`),
  UNIQUE INDEX `share_UNIQUE` (`share` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CREA2`.`Purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CREA2`.`Purchase` (
  `pk_idPurchase` INT NOT NULL AUTO_INCREMENT,
  `fk_Client` INT NOT NULL,
  `fk_Plan` INT NOT NULL,
  `fk_Subscription` INT NOT NULL,
  `transaction_date` DATETIME NOT NULL,
  `active` TINYINT(1) NOT NULL,
  PRIMARY KEY (`pk_idPurchase`),
  INDEX `fk_Purchase_Client_idx` (`fk_Client` ASC) VISIBLE,
  INDEX `fk_Purchase_Plan_idx` (`fk_Plan` ASC) VISIBLE,
  INDEX `fk_Purchase_Subscription_idx` (`fk_Subscription` ASC) VISIBLE,
  CONSTRAINT `fk_Purchase_Client`
    FOREIGN KEY (`fk_Client`)
    REFERENCES `CREA2`.`Client` (`pk_idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Purchase_Plan`
    FOREIGN KEY (`fk_Plan`)
    REFERENCES `CREA2`.`Plan` (`pk_idPlan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Purchase_Subscription`
    FOREIGN KEY (`fk_Subscription`)
    REFERENCES `CREA2`.`Subscription` (`pk_idSubscription`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CREA2`.`Concession`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CREA2`.`Concession` (
  `pk_idConcession` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pk_idConcession`),
  UNIQUE INDEX `type_UNIQUE` (`type` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CREA2`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CREA2`.`Admin` (
  `pk_idAdmin` INT NOT NULL AUTO_INCREMENT,
  `fk_idConcession` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`pk_idAdmin`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_Admin_Concession_idx` (`fk_idConcession` ASC) VISIBLE,
  CONSTRAINT `fk_Admin_Concession`
    FOREIGN KEY (`fk_idConcession`)
    REFERENCES `CREA2`.`Concession` (`pk_idConcession`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
