services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:5000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    ports: 
      - 33067:3306
    environment:
      MYSQL_DATABASE: crea
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - .dbdata:/var/lib/mysql